### ISSUE TITLE
[Bug] Outdated EmulatorJS versiom

### ISSUE THREAD

**Issue by EmPiFree** [rommapp/romm#1373]
**RomM version**
3.6.0

**Describe the bug**
I get the error "Outdated EmulatorJS version" when starting a core/rom

**To Reproduce**

1. Start any rom
2. See error

**Expected behavior**
Rom should start

**Screenshots**
![image](https://github.com/user-attachments/assets/58e73846-5bdd-4f97-8568-30cb931c3989)

**Desktop (please complete the following information):**

- OS: Win10
- Browser Brave and Edge
- Version: Most recent

**Additional context**
A new EmulatorJS update just has been released. We probably need to update the integrated EmulatorJS version.

**Comment by Acciden7Prone92** [comment]
I am also experiencing this issue - across all platforms.

**Comment by gantoine** [comment]
The issue is fix in the latest alpha release `3.7.0-alpha.1`, and will be generally available in the `3.7.0` release. I don't recommend upgrading to the alpha as we can't guarantee the image is stable.

**Comment by r-trigo** [comment]
I can see that `3.8.0-alpha-1` includes the EmulatorJS bump in the PR list, however this issue is occurring in my docker container.

**Comment by gantoine** [comment]
upgrade to 3.7.0-alpha.1, stop delete and restart the container, then clear browser cache

**Comment by MambaNerd** [comment]
I am also having the sam issue in my docker contaier

**Comment by r-trigo** [comment]
Sorry, I meant `3.7.0-alpha.1` (`3.8.0-alpha.1` is not released).
Clearing the cache after bumping to `3.7.0-alpha.1` did the trick, thanks 🙏

**Comment by hannibalshosting88** [comment]
Guess i'm having the same issue.  So the only fix is waiting for or upgrading to the alpha?

**Comment by gantoine** [comment]
Correct, though this should be the last time this happens as we're working with the emulatorjs team to make sure it doesn't happen again in the future, when they release next.

**Comment by whitenet** [comment]
updated to 3.7.1-alpha is still error with outdated emulatorJs

**Comment by gantoine** [comment]
@whitenet stop delete and restart the container, then clear browser cache

**Comment by hannibalshosting88** [comment]
Well, whatever any of you do, don't attempt to deploy the alpha If you have this thing running as a Docker in UnRAID.

**Comment by djismgaming** [comment]
> Well, whatever any of you do, don't attempt to deploy the alpha If you have this thing running as a Docker in UnRAID.

Will it do something bad? I have mine in unraid using docker compose. So far great.

**Comment by RegalMonkey** [comment]
Why would an outdated version of EmulatorJS actively prevent launching it? An update-availiable notification is all well and good, but to prevent the use of an older version because a new release came out is pretty over the top.

**Comment by hannibalshosting88** [comment]
> > Well, whatever any of you do, don't attempt to deploy the alpha If you have this thing running as a Docker in UnRAID.
> 
> Will it do something bad? I have mine in unraid using docker compose. So far great.

I've got mine running through the community applications plug-in.  When I adjusted the gui ( which is the same as adjusting a docker run or compose from what I understand) to pull the alpha branch mentioned,  it pulled successfully,  stopped my array, and rebooted unRAID. Not saying it's 100% caused by it,  but it happened lol.

**Comment by djismgaming** [comment]
> > > Well, whatever any of you do, don't attempt to deploy the alpha If you have this thing running as a Docker in UnRAID.
> > 
> > 
> > Will it do something bad? I have mine in unraid using docker compose. So far great.
> 
> I've got mine running through the community applications plug-in. When I adjusted the gui ( which is the same as adjusting a docker run or compose from what I understand) to pull the alpha branch mentioned, it pulled successfully, stopped my array, and rebooted unRAID. Not saying it's 100% caused by it, but it happened lol.

Thanks for that. Will keep on the lookout for something like this happening on my side. Thanks for the update. Definitely something to keep in mind.

**Comment by djismgaming** [comment]
> Why would an outdated version of EmulatorJS actively prevent launching it? An update-availiable notification is all well and good, but to prevent the use of an older version because a new release came out is pretty over the top.

At least it seems it's been addressed. Selfhosting something that can call home with the possibility to loose functionality is a little bit concerning. 100% not the fault of Romm, and very good for the developers to contact the upstream feature developers to circumvent this in the future.

**Comment by ItsNoted** [comment]
Hmmm. I am running 3.7.0-alpha.1 in Docker and it's still happening for me. Cleared cache, tried incognito, even tried a different browser compleptely.

**Comment by vitormarcal** [comment]
I'm running 3.7.0-alpha.1.  I tried different browser and it's still happening for me

**Comment by Iwasanity-dev** [comment]
Yeah same on me, tried everything - still happening for me too.

**Comment by pr0PM** [comment]
I checked the demo site, same error on it too.

**Comment by vitormarcal** [comment]
I update to 3.7.0-alpha.1, cleared browser data and it works!

**Comment by gantoine** [comment]
@pr0PM demo site should be fixed now, you'll need to clear browser cache for that site

**Comment by RobvanHamersveld** [comment]
I have the same issue. On latest, 3.7.0-alpha.1, 3.7.0-alpha.2 and 3.7.0-beta.1.

**Comment by RobvanHamersveld** [comment]
Issue seems to be resolved in 3.7.0-beta.3

**Comment by azithinkiam** [comment]
still getting this on unraid with -latest docker from community apps.  unable to determine version.  is it likely the community apps container has not yet been updated?  i've tried to manually use compose and the actual latest from here, but no luck yet...

TIA.

**Comment by azithinkiam** [comment]
> From the looks of this thread, you'll need to change the `:latest` tag to `:3.7.0-beta.3` for now in the Unraid template.
> Just press on the Edit option and change the `rommapp/romm` or `rommapp/romm:latest` to `rommapp/romm:3.7.0-beta.3`
--
Edit killed the container, but reinstalling from 'rommapp/romm:3.7.0-beta.3' seems to have done the trick.  THANK YOU - I was hoping it was something simple like that.  I hadn't had to deviate from default versions yet...

THANK YOU!

-t.

**Comment by gantoine** [comment]
With `v3.7.0` released and running EmulatorJS `v4.2.0` this issue has been addressed, and shouldn't occur again, as we're now pinning the emulatorjs version explicitly in code.
