### ISSUE TITLE
[Bug] Save state not saving to Romm

### ISSUE THREAD

**Issue by djinni74** [rommapp/romm#1708]
**RomM version**
3.8.0

**Describe the bug**
When I press the save state button when emulating a game the state doesn't get saved to Romm.

**To Reproduce**

1. Emulate game.
2. Click on 'save state'

**Expected behavior**
I expect the state to be saved to Romm so that it can be reloaded.

**Screenshots**

![Image](https://github.com/user-attachments/assets/b1a453d3-29e5-46ab-978d-841fd9c72a7d)

![Image](https://github.com/user-attachments/assets/ed5e1b4d-f08c-4283-a033-ba03c09ee1b0)

![Image](https://github.com/user-attachments/assets/26925d1e-f1b1-4295-985b-96b6f031da9c)

**Desktop (please complete the following information):**

- OS: Windows, MacOS
- Browser: Chrome 134.0.6998.37, Firefox 136.0, Safari (don't know the version)

**Additional context**

**Comment by gantoine** [comment]
This should be fixed in the next release.

**Comment by PaeyMoopy** [comment]
any timeframe? this is really frustrating.. I just set up Romm today and lost hours of playtime thinking it would save as the docs suggested.

**Comment by gantoine** [comment]
Sorry about that @PaeyMoopy, you can switch to `3.8.2-beta.1` now and give it a shot, it has all the fixes for emulatorjs we could.

**Comment by SpikeTheDragon40k** [comment]
Hello i tested with the latest beta but the problem seems still on. I'll test more and report back asap.

**Comment by PaeyMoopy** [comment]
yeah still not working even with the beta.. I can't trust it anymore, get too nervous when I save. 
Headed back to client based emulation. I'll keep an eye on this project for when this gets addressed and released (not beta).

**Comment by gantoine** [comment]
> Headed back to client based emulation.

This is preferred anyways, we always recommend playing on device with our playnite or muos apps (more apps coming soon) over playing in the browser.

https://github.com/rommapp/muos-app
https://github.com/rommapp/playnite-plugin

**Comment by gantoine** [comment]
> yeah still not working even with the beta.. I can't trust it anymore, get too nervous when I save.

@PaeyMoopy Are you saving or using the save state function?

**Comment by gantoine** [comment]
> Tried both but save state was the one I expected to work.

Can you do me a favour and try save states in incognito mode, or after clearing your cache? The structure changed in the beta and needs a clean slate.

> Need a way to make the cloud save hot-keyed

This isn't possible with emulatorjs at moment, nor is it something emujs can support even if we hack it together.
