### ISSUE TITLE
[Bug] Tinfoil feed is not aware of HTTPS settings in reverse proxy

### ISSUE THREAD

**Issue by ryuzio** [rommapp/romm#1737]
**RomM version**
v3.8.1

**Describe the bug**
Tinfoil integration is not aware of reverse proxy settings, thus creates feeds with `http` only. If the RomM expects users to use `https` only for serving files, Tinfoill will not work properly on game installation.

**To Reproduce**

1. Update the library with some switch games
2. Setup the instance with tinfoil integration according [official doc](https://docs.romm.app/latest/System-Setup/Tinfoil-Integration/)
3. Go to the tinfoil endpoint `/api/tinfoil/feed/` to see the list of files
4. See error in urls. All links seem to be in `http` regardless of reverse proxy settings of RomM

**Additional context**
Maybe have an environment variable as configuration item for creating urls in Tinfoil feed with `http` or `https`?

**Screenshots**

<img width="544" alt="Image" src="https://github.com/user-attachments/assets/00ceb5a9-e0ff-4c56-8377-c2147bc1fc75" />

**Comment by adamantike** [comment]
This should have been fixed a while ago, in #1077.  Do you use any custom nginx or Gunicorn configuration?

**Comment by ryuzio** [comment]
@adamantike Thank you for your quick reply! Yes, I have RomM deployed in Kubernetes, and the nginx is managed by the cluster's ingress controller. I'll double check the security headers in ingress configuration and see if it makes a difference.

**Comment by ryuzio** [comment]
I've tried security headers and https redirect, so far no luck. Since there are multiple configurations here that may affect the behaviour, may I ask what is the expected result for the fix? Shall I see `https` urls in the Tinfoil feed? Or shall I still see `http` in urls but expect https redirect from the reverse proxy to handle it?

**Comment by ryuzio** [comment]
Also, I'm using the provided docker image and noticed that it comes with a default nginx configuration inside the container as well. Maybe multiple layers of reverse proxies could also get things complicated for proxy headers?

**Comment by Josh19002** [comment]
I can also confirm that this is an issue, up to the latest release. When attempting an install on tinfoils end it does issue an alert saying that SSL failed. If I disable SSL on my NGINX proxy manager instance it works as intended, however, it fails whenever SSL is enabled. If you need additional information I am also willing to provide it.

**Comment by ryuzio** [comment]
I ended up making a monkey patch in `feeds.py` as a workaround. It works but in a very ugly way.
From that, I thought about raising a PR for a configuration item to force the scheme when generating urls, as I see it valuable in some use cases. However, it still looks pretty bad in code with awkward string manipulations around "http://" and "https://". I think such code will come back to haunt me if I really submit it, lol

Taking a step back and reading [the link on the original decription of the scheme issue in Starlette](https://github.com/encode/starlette/issues/538#issuecomment-2054013679), I think there could be something missing in current Gunicorn command. The post mentions 2 configurations `--proxy-headers` and `--forwarded-allow-ips=*`, while [current gunicorn launch command in romm](https://github.com/rommapp/romm/blob/release/docker/init_scripts/init#L57) only has `--forwarded-allow-ips=*`. I'll try adding `--proxy-headers` to the init file, with some proxy headers in my reverse proxy and see if it makes a difference. If it works, it will make a much cleaner solution.

**Comment by ryuzio** [comment]
OK, forget about that. After some testing, it turns out that `--proxy-headers` is for univcorn instead of Gunicorn. Adding it to the init script just gave me an error on unrecognized arguments.

Tracking down on uvicorn worker side, I see that the init script is using the default `uvicorn.workers.UvicornWorker`. I'm not familiar with uvicorn. Is `proxy_headers` set to True by default in the worker?

**Comment by gantoine** [comment]
@adamantike Know anything about this?

**Comment by starkmapper** [comment]
running the provided container behind an ssl-proxy causes this issue because of this line in the nginx config:

https://github.com/rommapp/romm/blob/8a1affba183d16b9a3eea20bbbc2b5b638018f72/docker/nginx/templates/default.conf.template#L13
```
    proxy_set_header X-Forwarded-Proto $scheme;
```
This should be:
```
    proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
```

Verified to work behind traefik ssl proxy.

**Comment by adamantike** [comment]
@starkmapper thanks for investigating the underlying issue.

I don't think your recommended solution is something we could merge, as it would break X-Forwarded-Proto when Nginx is accessed directly without an outer proxy terminating TLS connections before it.

Ideally, the PR to fix this issue for all installations is to use the $scheme variable as fallback.

**Comment by starkmapper** [comment]
I thought the same thing, but curl-ing the endpoint omdirectly on the nginx instance without ssl returned http links...

I have not investigated further though...

**Comment by starkmapper** [comment]
@adamantike @gantoine This should fix it, feel free to take a look whenever you can :-)
