### ISSUE TITLE
503 error: Can't connect to IGDB, but that source is not selected

### ISSUE THREAD

**Issue by chriscrutch** [rommapp/romm#867]
**RomM version**
3.1.0

**Describe the bug**
Trying to do a Quick Scan, I get a 503 error: Can't connect to IGDB, check internet connection.  I get the error even when IGDB is not selected as a source

**Expected behavior**
If IGDB is not selected as a source, I should not get an error message about not being able to reach IGDB

**Desktop (please complete the following information):**
 - OS: Debian testing
 - Browser: Firefox
 - Version: 126.0

**Additional context**
I don't know the limits of IGDB's API and I was adding files from a large library, I thought maybe I had exhausted API calls for a time, but even trying to run the scan with only MobyGames selected the error occurs.

**Comment by gantoine** [comment]
Oh cool find! I'll have a look tonight and likely have a fix out before the next release.

**Comment by gantoine** [comment]
@chriscrutch can you post the containers logs right after a scan?

**Comment by chriscrutch** [comment]
@gantoine 
Here you are:

[2024-05-22 12:51:09 -0400] [38] [INFO] None - "WebSocket /ws/socket.io/?EIO=4&transport=websocket" [accepted]

[2024-05-22 12:51:09 -0400] [38] [INFO] connection open

INFO:	  [RomM][2024-05-22 12:51:09] 🔎 Scanning 

12:51:09 high: endpoints.sockets.scan.scan_platforms([], <ScanType.QUICK: 'quick'>, [], ['moby']) (8b63bd32-4464-41aa-9530-edd0cf2f2dba)

INFO:	  [RomM][2024-05-22 12:51:10] Found 74 platforms in file system 

INFO:	  [RomM][2024-05-22 12:51:10] · n64

CRITICAL: [RomM][2024-05-22 12:51:15] Connection error: can't connect to IGDB

Traceback (most recent call last):

  File "/backend/lib/python3.11/site-packages/urllib3/connection.py", line 198, in _new_conn

    sock = connection.create_connection(

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/backend/lib/python3.11/site-packages/urllib3/util/connection.py", line 60, in create_connection

    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo

    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/backend/lib/python3.11/site-packages/urllib3/connectionpool.py", line 793, in urlopen

    response = self._make_request(

               ^^^^^^^^^^^^^^^^^^^

  File "/backend/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request

    raise new_e

  File "/backend/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request

    self._validate_conn(conn)

  File "/backend/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn

    conn.connect()

  File "/backend/lib/python3.11/site-packages/urllib3/connection.py", line 616, in connect

    self.sock = sock = self._new_conn()

                       ^^^^^^^^^^^^^^^^

  File "/backend/lib/python3.11/site-packages/urllib3/connection.py", line 205, in _new_conn

    raise NameResolutionError(self.host, self, e) from e

urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f647fe53fd0>: Failed to resolve 'api.igdb.com' ([Errno -3] Try again)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/backend/lib/python3.11/site-packages/requests/adapters.py", line 486, in send

    resp = conn.urlopen(

           ^^^^^^^^^^^^^

  File "/backend/lib/python3.11/site-packages/urllib3/connectionpool.py", line 847, in urlopen

    retries = retries.increment(

              ^^^^^^^^^^^^^^^^^^

  File "/backend/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment

    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]

    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.igdb.com', port=443): Max retries exceeded with url: /v4/platforms (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f647fe53fd0>: Failed to resolve 'api.igdb.com' ([Errno -3] Try again)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/backend/handler/metadata_handler/igdb_handler.py", line 161, in _request

    res = requests.post(

          ^^^^^^^^^^^^^^

  File "/backend/lib/python3.11/site-packages/requests/api.py", line 115, in post

    return request("post", url, data=data, json=json, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/backend/lib/python3.11/site-packages/requests/api.py", line 59, in request

    return session.request(method=method, url=url, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/backend/lib/python3.11/site-packages/requests/sessions.py", line 589, in request

    resp = self.send(prep, **send_kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/backend/lib/python3.11/site-packages/requests/sessions.py", line 703, in send

    r = adapter.send(request, **kwargs)

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/backend/lib/python3.11/site-packages/requests/adapters.py", line 519, in send

    raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.igdb.com', port=443): Max retries exceeded with url: /v4/platforms (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f647fe53fd0>: Failed to resolve 'api.igdb.com' ([Errno -3] Try again)"))

ERROR:	  [RomM][2024-05-22 12:51:15] 503: Can't connect to IGDB, check your internet connection

12:51:15 high: Job OK (8b63bd32-4464-41aa-9530-edd0cf2f2dba)

12:51:15 Result is kept for 500 seconds

INFO:	  [nginx][2024-05-22 ]	100.114.136.83 - - "GET /ws/socket.io/?EIO=4&transport=websocket HTTP/1.1" 101 186 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0" rt=11.275 uct="0.000" uht="4.460" urt="11.276"

[2024-05-22 12:51:16 -0400] [38] [INFO] connection closed

**Comment by gantoine** [comment]
> Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f647fe53fd0>: Failed to resolve 'api.igdb.com' ([Errno -3] Try again)")

Seems it's dropping the connection to IGDB after some time and not able to recover. Waiting a little while and restarting the scan often "fixes" the issue.

**Comment by chriscrutch** [comment]
>  Waiting a little while and restarting the scan often "fixes" the issue.

Hasn't in this case. It has persisted for the last 36 hours and through re-starting the Docker container.

**Comment by chriscrutch** [comment]
The issue has resolved now, I guess. After several days I was able to access IGDB again (API call limit reset, maybe?) and the scans work fine. Whatever was keeping me from accessing IGDB still shouldn't have caused an error when scanning without IGDB, however.

**Comment by gantoine** [comment]
Got a fix for this here anyways, so hopefully it doesn't happen next time you get rate limited! https://github.com/rommapp/romm/pull/882

> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.igdb.com', port=443): Max retries exceeded with url: /v4/platforms (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f647fe53fd0>: Failed to resolve 'api.igdb.com' ([Errno -3] Try again)"))

**Comment by chriscrutch** [comment]
Thank you!

**Comment by zerojay** [comment]
This is still happening in 3.2.0. Even with IGDB not selected as a metadata provider, it will respond saying IGDB cannot be connected to and abort everything. With IGDB and Moby both failing, and since there appears to be no way to add games without metadata, this application ends up being useless when API limits are hit or the metadata sources are down.

**Comment by berturion** [comment]
I have this issue too, in 3.2.0. The scan break when hitting this error:

```
Jun 24 13:47:37 sheldon docker/romm[6094]: INFO:          [RomM][2024-06-24 11:47:37]            Identified as Steel Talons 👾
Jun 24 13:47:43 sheldon docker/romm[6094]: INFO:          [RomM][2024-06-24 11:47:43]          · Bass Masters Classic (U).smc
Jun 24 13:47:46 sheldon docker/romm[6094]: INFO:          [RomM][2024-06-24 11:47:46]            Identified as Bass Masters Classic: Pro Edition 👾
Jun 24 13:47:54 sheldon docker/romm[6094]: INFO:          [RomM][2024-06-24 11:47:54]          · Final Fantasy II - The Non-Cheeseball Edition (Hack).smc
Jun 24 13:48:03 sheldon docker/romm[6094]: CRITICAL: [RomM][2024-06-24 11:48:03] Connection error: can't connect to IGDB
Jun 24 13:48:03 sheldon docker/romm[6094]: Traceback (most recent call last):
Jun 24 13:48:03 sheldon docker/romm[6094]:   File "/backend/lib/python3.11/site-packages/urllib3/connection.py", line 198, in _new_conn
Jun 24 13:48:03 sheldon docker/romm[6094]:     sock = connection.create_connection(
Jun 24 13:48:03 sheldon docker/romm[6094]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 24 13:48:03 sheldon docker/romm[6094]:   File "/backend/lib/python3.11/site-packages/urllib3/util/connection.py", line 60, in create_connection
Jun 24 13:48:03 sheldon docker/romm[6094]:     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
Jun 24 13:48:03 sheldon docker/romm[6094]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 24 13:48:03 sheldon docker/romm[6094]:   File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
Jun 24 13:48:03 sheldon docker/romm[6094]:     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Jun 24 13:48:03 sheldon docker/romm[6094]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 24 13:48:03 sheldon docker/romm[6094]: socket.gaierror: [Errno -3] Try again
Jun 24 13:48:03 sheldon docker/romm[6094]:
Jun 24 13:48:03 sheldon docker/romm[6094]: The above exception was the direct cause of the following exception:
Jun 24 13:48:03 sheldon docker/romm[6094]:
Jun 24 13:48:03 sheldon docker/romm[6094]: Traceback (most recent call last):
Jun 24 13:48:03 sheldon docker/romm[6094]:   File "/backend/lib/python3.11/site-packages/urllib3/connectionpool.py", line 793, in urlopen
Jun 24 13:48:03 sheldon docker/romm[6094]:     response = self._make_request(
Jun 24 13:48:03 sheldon docker/romm[6094]:                ^^^^^^^^^^^^^^^^^^^
Jun 24 13:48:03 sheldon docker/romm[6094]:   File "/backend/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
Jun 24 13:48:03 sheldon docker/romm[6094]:     raise new_e
Jun 24 13:48:03 sheldon docker/romm[6094]:   File "/backend/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
Jun 24 13:48:03 sheldon docker/romm[6094]:     self._validate_conn(conn)
Jun 24 13:48:03 sheldon docker/romm[6094]:   File "/backend/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
Jun 24 13:48:03 sheldon docker/romm[6094]:     conn.connect()
Jun 24 13:48:03 sheldon docker/romm[6094]:   File "/backend/lib/python3.11/site-packages/urllib3/connection.py", line 616, in connect
Jun 24 13:48:03 sheldon docker/romm[6094]:     self.sock = sock = self._new_conn()
Jun 24 13:48:03 sheldon docker/romm[6094]:                        ^^^^^^^^^^^^^^^^
Jun 24 13:48:03 sheldon docker/romm[6094]:   File "/backend/lib/python3.11/site-packages/urllib3/connection.py", line 205, in _new_conn
Jun 24 13:48:03 sheldon docker/romm[6094]:     raise NameResolutionError(self.host, self, e) from e
Jun 24 13:48:03 sheldon docker/romm[6094]: urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7679a86fa4d0>: Failed to resolve 'api.igdb.com' ([Errno -3] Try again)
Jun 24 13:48:03 sheldon docker/romm[6094]:
Jun 24 13:48:03 sheldon docker/romm[6094]: The above exception was the direct cause of the following exception:
Jun 24 13:48:03 sheldon docker/romm[6094]:
Jun 24 13:48:03 sheldon docker/romm[6094]: Traceback (most recent call last):
Jun 24 13:48:03 sheldon docker/romm[6094]:   File "/backend/lib/python3.11/site-packages/requests/adapters.py", line 564, in send
Jun 24 13:48:03 sheldon docker/romm[6094]:     resp = conn.urlopen(
Jun 24 13:48:03 sheldon docker/romm[6094]:            ^^^^^^^^^^^^^
Jun 24 13:48:03 sheldon docker/romm[6094]:   File "/backend/lib/python3.11/site-packages/urllib3/connectionpool.py", line 847, in urlopen
Jun 24 13:48:03 sheldon docker/romm[6094]:     retries = retries.increment(
Jun 24 13:48:03 sheldon docker/romm[6094]:               ^^^^^^^^^^^^^^^^^^
Jun 24 13:48:03 sheldon docker/romm[6094]:   File "/backend/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
Jun 24 13:48:03 sheldon docker/romm[6094]:     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
Jun 24 13:48:03 sheldon docker/romm[6094]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 24 13:48:03 sheldon docker/romm[6094]: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.igdb.com', port=443): Max retries exceeded with url: /v4/search (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7679a86fa4d0>: Failed to resolve 'api.igdb.com' ([Errno -3] Try again)"))
Jun 24 13:48:03 sheldon docker/romm[6094]:
Jun 24 13:48:03 sheldon docker/romm[6094]: During handling of the above exception, another exception occurred:
Jun 24 13:48:03 sheldon docker/romm[6094]:
Jun 24 13:48:03 sheldon docker/romm[6094]: Traceback (most recent call last):
Jun 24 13:48:03 sheldon docker/romm[6094]:   File "/backend/handler/metadata/igdb_handler.py", line 161, in _request
Jun 24 13:48:03 sheldon docker/romm[6094]:     res = requests.post(
Jun 24 13:48:03 sheldon docker/romm[6094]:           ^^^^^^^^^^^^^^
Jun 24 13:48:03 sheldon docker/romm[6094]:   File "/backend/lib/python3.11/site-packages/requests/api.py", line 115, in post
Jun 24 13:48:03 sheldon docker/romm[6094]:     return request("post", url, data=data, json=json, **kwargs)
Jun 24 13:48:03 sheldon docker/romm[6094]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 24 13:48:03 sheldon docker/romm[6094]:   File "/backend/lib/python3.11/site-packages/requests/api.py", line 59, in request
Jun 24 13:48:03 sheldon docker/romm[6094]:     return session.request(method=method, url=url, **kwargs)
Jun 24 13:48:03 sheldon docker/romm[6094]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 24 13:48:03 sheldon docker/romm[6094]:   File "/backend/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
Jun 24 13:48:03 sheldon docker/romm[6094]:     resp = self.send(prep, **send_kwargs)
Jun 24 13:48:03 sheldon docker/romm[6094]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 24 13:48:03 sheldon docker/romm[6094]:   File "/backend/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
Jun 24 13:48:03 sheldon docker/romm[6094]:     r = adapter.send(request, **kwargs)
Jun 24 13:48:03 sheldon docker/romm[6094]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 24 13:48:03 sheldon docker/romm[6094]:   File "/backend/lib/python3.11/site-packages/requests/adapters.py", line 597, in send
Jun 24 13:48:03 sheldon docker/romm[6094]:     raise ConnectionError(e, request=request)
Jun 24 13:48:03 sheldon docker/romm[6094]: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.igdb.com', port=443): Max retries exceeded with url: /v4/search (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7679a86fa4d0>: Failed to resolve 'api.igdb.com' ([Errno -3] Try again)"))
Jun 24 13:48:03 sheldon docker/romm[6094]: ERROR:          [RomM][2024-06-24 11:48:03] 503: Can't connect to IGDB, check your internet connection
Jun 24 13:48:03 sheldon docker/romm[6094]: 11:48:03 high: Job OK (34c5efc8-7350-4b8d-9f7f-a0e740d8dd4e)
Jun 24 13:48:03 sheldon docker/romm[6094]: 11:48:03 Result is kept for 500 seconds
Jun 24 13:48:03 sheldon docker/romm[6094]: 11:48:03 Cleaning registries for queue: high
Jun 24 13:48:03 sheldon docker/romm[6094]: INFO:          [nginx][2024-06-24 11:48:03]        172.26.0.1 - - "GET /ws/socket.io/?EIO=4&transport=websocket HTTP/1.0" 101 17588 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" rt=389.962 uct="0.000" uht="0.018" urt="389.961"
Jun 24 13:48:03 sheldon docker/romm[6094]: 11:48:03 Cleaning registries for queue: default
Jun 24 13:48:03 sheldon docker/romm[6094]: [2024-06-24 11:48:03 +0000] [24] [INFO] connection closed
Jun 24 13:48:03 sheldon docker/romm[6094]: 11:48:03 Cleaning registries for queue: low
Jun 24 13:48:36 sheldon docker/romm[6094]: 11:M 24 Jun 2024 11:48:36.089 * 100 changes in 300 seconds. Saving...
Jun 24 13:48:36 sheldon docker/romm[6094]: 11:M 24 Jun 2024 11:48:36.094 * Background saving started by pid 16366
Jun 24 13:48:36 sheldon docker/romm[6094]: 16366:C 24 Jun 2024 11:48:36.681 * DB saved on disk
Jun 24 13:48:36 sheldon docker/romm[6094]: 16366:C 24 Jun 2024 11:48:36.684 * Fork CoW for RDB: current 1 MB, peak 1 MB, average 1 MB
Jun 24 13:48:36 sheldon docker/romm[6094]: 11:M 24 Jun 2024 11:48:36.696 * Background saving terminated with success
```

I must relaunch a scan to continue the process of importing my library.
The error occurs after about 100 or 200 games added but my library is 1500+ games large. It is not blocking but annoying.

Thanks for maintaining this awesome project though.

**Comment by gantoine** [comment]
@berturion You issue we'll deal with in #861, and @zerojay I'll have a look when I find some time!
